# Generated by Django 5.2.6 on 2025-09-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),  # agar users app me User model ke liye migration hai
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('village_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(max_digits=9, decimal_places=6)),
                ('longitude', models.DecimalField(max_digits=9, decimal_places=6)),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('village_id', models.IntegerField()),
                ('symptoms', models.TextField()),
                ('severity', models.CharField(
                    choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')],
                    max_length=10
                )),
                ('date_of_reporting', models.DateField()),
                ('water_source', models.CharField(max_length=100)),
                ('treatment_given', models.TextField()),
                ('asha_worker_id', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NgoSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_drinking_water', models.BooleanField(default=False)),
                ('toilet_coverage', models.PositiveIntegerField(default=0)),
                ('waste_disposal_system', models.BooleanField(default=False)),
                ('flooding_waterlogging', models.BooleanField(default=False)),
                ('awareness_campaigns', models.BooleanField(default=False)),
                ('typhoid_cases', models.PositiveIntegerField(default=0)),
                ('fever_cases', models.PositiveIntegerField(default=0)),
                ('diarrhea_cases', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.Village')),
            ],
        ),
        migrations.CreateModel(
            name='Ngo_HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reporting', models.DateField()),
                ('cases', models.PositiveIntegerField(default=0)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthreports', to='data_collection.Village')),
            ],
        ),
    ]
