# Generated by Django 5.2.6 on 2025-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reporting', models.DateField()),
                ('cases', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NgoSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_drinking_water', models.BooleanField(default=False)),
                ('toilet_coverage', models.PositiveIntegerField(default=0)),
                ('waste_disposal_system', models.BooleanField(default=False)),
                ('flooding_waterlogging', models.BooleanField(default=False)),
                ('awareness_campaigns', models.BooleanField(default=False)),
                ('typhoid_cases', models.PositiveIntegerField(default=0)),
                ('fever_cases', models.PositiveIntegerField(default=0)),
                ('diarrhea_cases', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_id', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
