# Generated by Django 5.2.6 on 2025-09-15 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_reporting', models.DateField()),
                ('typhoid_cases', models.IntegerField(default=0)),
                ('fever_cases', models.IntegerField(default=0)),
                ('diarrhea_cases', models.IntegerField(default=0)),
                ('cholera_cases', models.IntegerField(default=0)),
                ('hospitalized_cases', models.IntegerField(default=0)),
                ('deaths_reported', models.IntegerField(default=0)),
                ('village', models.CharField(default='Not specified', max_length=100)),
                ('district', models.CharField(default='Not specified', max_length=100)),
                ('state', models.CharField(default='Not specified', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
