# Generated by Django 5.2.6 on 2025-09-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
    ]
