# Generated by Django 5.2.6 on 2025-09-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ngosurvey',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ngosurvey',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.village'),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthreports', to='data_collection.village'),
        ),
    ]
