# Generated by Django 5.2.6 on 2025-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreport',
            name='village',
            field=models.CharField(max_length=100),
        ),
    ]
