# Generated by Django 5.2.6 on 2025-09-14 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_alter_healthreport_village'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ngosurvey',
            name='district',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='ngosurvey',
            name='state',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='ngosurvey',
            name='ngo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngosurvey',
            name='village',
            field=models.CharField(max_length=255),
        ),
    ]
