# Generated by Django 5.2.6 on 2025-09-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_alter_healthreport_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typhoid_cases', models.PositiveIntegerField(default=0)),
                ('fever_cases', models.PositiveIntegerField(default=0)),
                ('diarrhea_cases', models.PositiveIntegerField(default=0)),
                ('cholera_cases', models.PositiveIntegerField(default=0)),
                ('hospitalized_cases', models.PositiveIntegerField(default=0)),
                ('deaths_reported', models.PositiveIntegerField(default=0)),
                ('date_of_reporting', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.village')),
            ],
        ),
    ]
