# Generated by Django 5.2.6 on 2025-09-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_ngosurvey_district_ngosurvey_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='healthreport',
        #     name='district',
        # ),
        # migrations.RemoveField(
        #     model_name='healthreport',
        #     name='state',
        # ),
        # migrations.RemoveField(
        #     model_name='healthreport',
        #     name='village_id',
        # ),
        migrations.RemoveField(
            model_name='ngosurvey',
            name='district',
        ),
        migrations.RemoveField(
            model_name='ngosurvey',
            name='state',
        ),
        # migrations.AddField(
        #     model_name='village',
        #     name='population',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='healthreport',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports_set', to='data_collection.village'),
        ),
        migrations.AlterField(
            model_name='ngosurvey',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngosurvey',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.village'),
        ),
        # migrations.CreateModel(
        #     name='ClinicReport',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('typhoid_cases', models.PositiveIntegerField(default=0)),
        #         ('fever_cases', models.PositiveIntegerField(default=0)),
        #         ('diarrhea_cases', models.PositiveIntegerField(default=0)),
        #         ('cholera_cases', models.PositiveIntegerField(default=0)),
        #         ('hospitalized_cases', models.PositiveIntegerField(default=0)),
        #         ('deaths_reported', models.PositiveIntegerField(default=0)),
        #         ('date_of_reporting', models.DateField()),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.village')),
        #     ],
        # ),
    ]
