# Generated by Django 5.2.6 on 2025-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0004_remove_healthreport_district_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='village',
        #     name='population',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
