# Generated by Django 5.2.6 on 2025-09-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0005_village_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='village_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='water_quality',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Moderate', 'Moderate'), ('Poor', 'Poor')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='village',
            table='data_collection_village',
        ),
    ]
