# Generated by Django 5.2.6 on 2025-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0006_healthreport_district_healthreport_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicreport',
            name='id',
        ),
        migrations.AddField(
            model_name='clinicreport',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
