# Generated by Django 5.2.6 on 2025-09-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='extensions"."users_user',
        ),
    ]
