# Generated by Django 5.2.6 on 2025-09-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='extensions"."users_user',
        ),
    ]
