# Generated by Django 5.2.6 on 2025-09-16 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0004_initial_data_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('hospitalized_cases', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='Very Low', max_length=20)),
                ('risk_percentage', models.FloatField(blank=True, null=True)),
                ('latest_rb_alerts', models.TextField(blank=True, null=True)),
                ('symptom_distribution', models.JSONField(default=dict)),
                ('severity_distribution', models.JSONField(default=dict)),
                ('monthly_trend', models.JSONField(default=dict)),
                ('last_aggregated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_rows', to='data_collection.village')),
            ],
            options={
                'ordering': ['-last_aggregated_at'],
            },
        ),
    ]
