# Generated by Django 5.2.6 on 2025-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagedashboard',
            name='completed_campaigns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagedashboard',
            name='critical_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagedashboard',
            name='current_admissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagedashboard',
            name='latest_water_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagedashboard',
            name='latest_water_assessment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='villagedashboard',
            name='ongoing_campaigns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagedashboard',
            name='planned_campaigns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagedashboard',
            name='recovered_cases',
            field=models.IntegerField(default=0),
        ),
    ]
