# Generated by Django 5.2.6 on 2025-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_villagedashboard_completed_campaigns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagedashboard',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
